replicaCount: 1
image:
  repository: ai-image-optimizer-k3s
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: ai.infranerd.de
  tlsSecret: wildcard-infranerd-tls

resources:
  limits:
    cpu: "4"
    memory: "8Gi"

persistence:
  enabled: true
  size: 10Gi
