stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/ai-image-optimizer-k3s:latest"
  KUBECONFIG: "/home/runner/.kube/config"

build:
  stage: build
  tags:
    - local-runner
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t $IMAGE_NAME ./app
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  tags:
    - local-runner
  script:
    - helm upgrade --install ai-image-optimizer ./charts/ai-image-optimizer \
        --set image.repository=$IMAGE_NAME \
        --namespace default
