
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-image-optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-image-optimizer
  template:
    metadata:
      labels:
        app: ai-image-optimizer
    spec:
      containers:
      - name: ai-image-optimizer
        image: ai-image-optimizer:latest
        ports:
        - containerPort: 7860
        volumeMounts:
        - name: image-storage
          mountPath: /data
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: image-pvc
