apiVersion: v1
kind: Service
metadata:
  name: ai-image-optimizer
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  selector:
    app: ai-image-optimizer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  type: {{ .Values.service.type }}
