name: Build & Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build & Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s:latest ./app
        docker push ${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s:latest

    - name: Helm Deploy to K3s
      run: |
        helm upgrade --install ai-image-optimizer ./charts/ai-image-optimizer \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s \
          --set image.tag=latest \
          --namespace default
