name: Build & Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build & Push with short SHA Tag
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s:$SHORT_SHA ./app
        docker push ${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s:$SHORT_SHA

    - name: Helm Deploy to K3s (atomic + wait)
      env:
        KUBECONFIG: /home/runner/.kube/config
      run: |
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        helm upgrade --install ai-image-optimizer ./charts/ai-image-optimizer \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s \
          --set image.tag=$SHORT_SHA \
          --set image.pullPolicy=Always \
          --namespace default \
          --atomic --wait

    - name: Cleanup unused images
      run: docker image prune -f
