
name: Deploy AI Image Optimizer

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build & Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s:latest ./app
        docker push ${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s:latest

    - name: Setup K8s (k3s)
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy Helm Chart to k3s
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        helm upgrade --install ai-image-optimizer ./charts/ai-image-optimizer           --set image.repository=${{ secrets.DOCKER_USERNAME }}/ai-image-optimizer-k3s           --set image.tag=latest           --namespace default
